//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace ChildDataPIN.BLL.Entities.BASE
{
    [DataContract(IsReference = false)]
    [KnownType(typeof(Coordinador))]
    [KnownType(typeof(Persona))]
    [KnownType(typeof(EstadoEntidad))]
    public partial class Entidad: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public System.Guid IdEntidad
        {
            get { return _idEntidad; }
            set
            {
                if (_idEntidad != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'IdEntidad' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _idEntidad = value;
                    OnPropertyChanged("IdEntidad");
                }
            }
        }
        private System.Guid _idEntidad;
    
        [DataMember]
        public System.Guid IdTipoEntidad
        {
            get { return _idTipoEntidad; }
            set
            {
                if (_idTipoEntidad != value)
                {
                    _idTipoEntidad = value;
                    OnPropertyChanged("IdTipoEntidad");
                }
            }
        }
        private System.Guid _idTipoEntidad;
    
        [DataMember]
        public System.Guid IdEstadoEntidad
        {
            get { return _idEstadoEntidad; }
            set
            {
                if (_idEstadoEntidad != value)
                {
                    ChangeTracker.RecordOriginalValue("IdEstadoEntidad", _idEstadoEntidad);
                    if (!IsDeserializing)
                    {
                        if (EstadoEntidad != null && EstadoEntidad.IdEstadoEntidad != value)
                        {
                            EstadoEntidad = null;
                        }
                    }
                    _idEstadoEntidad = value;
                    OnPropertyChanged("IdEstadoEntidad");
                }
            }
        }
        private System.Guid _idEstadoEntidad;
    
        [DataMember]
        public System.Guid IdTipoIdentificacion
        {
            get { return _idTipoIdentificacion; }
            set
            {
                if (_idTipoIdentificacion != value)
                {
                    _idTipoIdentificacion = value;
                    OnPropertyChanged("IdTipoIdentificacion");
                }
            }
        }
        private System.Guid _idTipoIdentificacion;
    
        [DataMember]
        public string CodigoIdentificacion
        {
            get { return _codigoIdentificacion; }
            set
            {
                if (_codigoIdentificacion != value)
                {
                    _codigoIdentificacion = value;
                    OnPropertyChanged("CodigoIdentificacion");
                }
            }
        }
        private string _codigoIdentificacion;
    
        [DataMember]
        public string Direccion
        {
            get { return _direccion; }
            set
            {
                if (_direccion != value)
                {
                    _direccion = value;
                    OnPropertyChanged("Direccion");
                }
            }
        }
        private string _direccion;
    
        [DataMember]
        public Nullable<int> Telefono
        {
            get { return _telefono; }
            set
            {
                if (_telefono != value)
                {
                    _telefono = value;
                    OnPropertyChanged("Telefono");
                }
            }
        }
        private Nullable<int> _telefono;
    
        [DataMember]
        public string Email
        {
            get { return _email; }
            set
            {
                if (_email != value)
                {
                    _email = value;
                    OnPropertyChanged("Email");
                }
            }
        }
        private string _email;
    
        [DataMember]
        public System.Guid CreadoPorIdUsuario
        {
            get { return _creadoPorIdUsuario; }
            set
            {
                if (_creadoPorIdUsuario != value)
                {
                    _creadoPorIdUsuario = value;
                    OnPropertyChanged("CreadoPorIdUsuario");
                }
            }
        }
        private System.Guid _creadoPorIdUsuario;
    
        [DataMember]
        public string CreadoEn
        {
            get { return _creadoEn; }
            set
            {
                if (_creadoEn != value)
                {
                    _creadoEn = value;
                    OnPropertyChanged("CreadoEn");
                }
            }
        }
        private string _creadoEn;
    
        [DataMember]
        public System.DateTime CreadoEl
        {
            get { return _creadoEl; }
            set
            {
                if (_creadoEl != value)
                {
                    _creadoEl = value;
                    OnPropertyChanged("CreadoEl");
                }
            }
        }
        private System.DateTime _creadoEl;
    
        [DataMember]
        public System.Guid ModificadoPorIdUsuario
        {
            get { return _modificadoPorIdUsuario; }
            set
            {
                if (_modificadoPorIdUsuario != value)
                {
                    _modificadoPorIdUsuario = value;
                    OnPropertyChanged("ModificadoPorIdUsuario");
                }
            }
        }
        private System.Guid _modificadoPorIdUsuario;
    
        [DataMember]
        public string ModificadoEn
        {
            get { return _modificadoEn; }
            set
            {
                if (_modificadoEn != value)
                {
                    _modificadoEn = value;
                    OnPropertyChanged("ModificadoEn");
                }
            }
        }
        private string _modificadoEn;
    
        [DataMember]
        public System.DateTime ModificadoEl
        {
            get { return _modificadoEl; }
            set
            {
                if (_modificadoEl != value)
                {
                    _modificadoEl = value;
                    OnPropertyChanged("ModificadoEl");
                }
            }
        }
        private System.DateTime _modificadoEl;

        #endregion
        #region Navigation Properties
    
        [DataMember]
        public TrackableCollection<Coordinador> Coordinador
        {
            get
            {
                if (_coordinador == null)
                {
                    _coordinador = new TrackableCollection<Coordinador>();
                    _coordinador.CollectionChanged += FixupCoordinador;
                }
                return _coordinador;
            }
            set
            {
                if (!ReferenceEquals(_coordinador, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_coordinador != null)
                    {
                        _coordinador.CollectionChanged -= FixupCoordinador;
                    }
                    _coordinador = value;
                    if (_coordinador != null)
                    {
                        _coordinador.CollectionChanged += FixupCoordinador;
                    }
                    OnNavigationPropertyChanged("Coordinador");
                }
            }
        }
        private TrackableCollection<Coordinador> _coordinador;
    
        [DataMember]
        public TrackableCollection<Persona> Persona
        {
            get
            {
                if (_persona == null)
                {
                    _persona = new TrackableCollection<Persona>();
                    _persona.CollectionChanged += FixupPersona;
                }
                return _persona;
            }
            set
            {
                if (!ReferenceEquals(_persona, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_persona != null)
                    {
                        _persona.CollectionChanged -= FixupPersona;
                    }
                    _persona = value;
                    if (_persona != null)
                    {
                        _persona.CollectionChanged += FixupPersona;
                    }
                    OnNavigationPropertyChanged("Persona");
                }
            }
        }
        private TrackableCollection<Persona> _persona;
    
        [DataMember]
        public EstadoEntidad EstadoEntidad
        {
            get { return _estadoEntidad; }
            set
            {
                if (!ReferenceEquals(_estadoEntidad, value))
                {
                    var previousValue = _estadoEntidad;
                    _estadoEntidad = value;
                    FixupEstadoEntidad(previousValue);
                    OnNavigationPropertyChanged("EstadoEntidad");
                }
            }
        }
        private EstadoEntidad _estadoEntidad;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            Coordinador.Clear();
            Persona.Clear();
            EstadoEntidad = null;
        }

        #endregion
        #region Association Fixup
    
        private void FixupEstadoEntidad(EstadoEntidad previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.Entidad.Contains(this))
            {
                previousValue.Entidad.Remove(this);
            }
    
            if (EstadoEntidad != null)
            {
                if (!EstadoEntidad.Entidad.Contains(this))
                {
                    EstadoEntidad.Entidad.Add(this);
                }
    
                IdEstadoEntidad = EstadoEntidad.IdEstadoEntidad;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("EstadoEntidad")
                    && (ChangeTracker.OriginalValues["EstadoEntidad"] == EstadoEntidad))
                {
                    ChangeTracker.OriginalValues.Remove("EstadoEntidad");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("EstadoEntidad", previousValue);
                }
                if (EstadoEntidad != null && !EstadoEntidad.ChangeTracker.ChangeTrackingEnabled)
                {
                    EstadoEntidad.StartTracking();
                }
            }
        }
    
        private void FixupCoordinador(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (Coordinador item in e.NewItems)
                {
                    item.Entidad = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("Coordinador", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Coordinador item in e.OldItems)
                {
                    if (ReferenceEquals(item.Entidad, this))
                    {
                        item.Entidad = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("Coordinador", item);
                    }
                }
            }
        }
    
        private void FixupPersona(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (Persona item in e.NewItems)
                {
                    item.Entidad = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("Persona", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Persona item in e.OldItems)
                {
                    if (ReferenceEquals(item.Entidad, this))
                    {
                        item.Entidad = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("Persona", item);
                    }
                }
            }
        }

        #endregion
    }
}
