//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace ChildDataPIN.BLL.Entities.BASE
{
    [DataContract(IsReference = false)]
    [KnownType(typeof(Entidad))]
    [KnownType(typeof(EstadoPersona))]
    public partial class Persona: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public System.Guid IdPersona
        {
            get { return _idPersona; }
            set
            {
                if (_idPersona != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'IdPersona' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _idPersona = value;
                    OnPropertyChanged("IdPersona");
                }
            }
        }
        private System.Guid _idPersona;
    
        [DataMember]
        public System.Guid IdEntidad
        {
            get { return _idEntidad; }
            set
            {
                if (_idEntidad != value)
                {
                    ChangeTracker.RecordOriginalValue("IdEntidad", _idEntidad);
                    if (!IsDeserializing)
                    {
                        if (Entidad != null && Entidad.IdEntidad != value)
                        {
                            Entidad = null;
                        }
                    }
                    _idEntidad = value;
                    OnPropertyChanged("IdEntidad");
                }
            }
        }
        private System.Guid _idEntidad;
    
        [DataMember]
        public System.Guid IdEstadoPersona
        {
            get { return _idEstadoPersona; }
            set
            {
                if (_idEstadoPersona != value)
                {
                    ChangeTracker.RecordOriginalValue("IdEstadoPersona", _idEstadoPersona);
                    if (!IsDeserializing)
                    {
                        if (EstadoPersona != null && EstadoPersona.IdEstadoPersona != value)
                        {
                            EstadoPersona = null;
                        }
                    }
                    _idEstadoPersona = value;
                    OnPropertyChanged("IdEstadoPersona");
                }
            }
        }
        private System.Guid _idEstadoPersona;
    
        [DataMember]
        public string PrimerNombre
        {
            get { return _primerNombre; }
            set
            {
                if (_primerNombre != value)
                {
                    _primerNombre = value;
                    OnPropertyChanged("PrimerNombre");
                }
            }
        }
        private string _primerNombre;
    
        [DataMember]
        public string SegundoNombre
        {
            get { return _segundoNombre; }
            set
            {
                if (_segundoNombre != value)
                {
                    _segundoNombre = value;
                    OnPropertyChanged("SegundoNombre");
                }
            }
        }
        private string _segundoNombre;
    
        [DataMember]
        public string PrimerApellido
        {
            get { return _primerApellido; }
            set
            {
                if (_primerApellido != value)
                {
                    _primerApellido = value;
                    OnPropertyChanged("PrimerApellido");
                }
            }
        }
        private string _primerApellido;
    
        [DataMember]
        public string SegundoApellido
        {
            get { return _segundoApellido; }
            set
            {
                if (_segundoApellido != value)
                {
                    _segundoApellido = value;
                    OnPropertyChanged("SegundoApellido");
                }
            }
        }
        private string _segundoApellido;
    
        [DataMember]
        public Nullable<int> Celular
        {
            get { return _celular; }
            set
            {
                if (_celular != value)
                {
                    _celular = value;
                    OnPropertyChanged("Celular");
                }
            }
        }
        private Nullable<int> _celular;
    
        [DataMember]
        public System.Guid IdTipoSexo
        {
            get { return _idTipoSexo; }
            set
            {
                if (_idTipoSexo != value)
                {
                    _idTipoSexo = value;
                    OnPropertyChanged("IdTipoSexo");
                }
            }
        }
        private System.Guid _idTipoSexo;
    
        [DataMember]
        public string FechaNacimiento
        {
            get { return _fechaNacimiento; }
            set
            {
                if (_fechaNacimiento != value)
                {
                    _fechaNacimiento = value;
                    OnPropertyChanged("FechaNacimiento");
                }
            }
        }
        private string _fechaNacimiento;
    
        [DataMember]
        public string Nota
        {
            get { return _nota; }
            set
            {
                if (_nota != value)
                {
                    _nota = value;
                    OnPropertyChanged("Nota");
                }
            }
        }
        private string _nota;
    
        [DataMember]
        public System.Guid CreadoPorIdUsuario
        {
            get { return _creadoPorIdUsuario; }
            set
            {
                if (_creadoPorIdUsuario != value)
                {
                    _creadoPorIdUsuario = value;
                    OnPropertyChanged("CreadoPorIdUsuario");
                }
            }
        }
        private System.Guid _creadoPorIdUsuario;
    
        [DataMember]
        public string CreadoEn
        {
            get { return _creadoEn; }
            set
            {
                if (_creadoEn != value)
                {
                    _creadoEn = value;
                    OnPropertyChanged("CreadoEn");
                }
            }
        }
        private string _creadoEn;
    
        [DataMember]
        public System.DateTime CreadoEl
        {
            get { return _creadoEl; }
            set
            {
                if (_creadoEl != value)
                {
                    _creadoEl = value;
                    OnPropertyChanged("CreadoEl");
                }
            }
        }
        private System.DateTime _creadoEl;
    
        [DataMember]
        public System.Guid ModificadoPorIdUsuario
        {
            get { return _modificadoPorIdUsuario; }
            set
            {
                if (_modificadoPorIdUsuario != value)
                {
                    _modificadoPorIdUsuario = value;
                    OnPropertyChanged("ModificadoPorIdUsuario");
                }
            }
        }
        private System.Guid _modificadoPorIdUsuario;
    
        [DataMember]
        public string ModificadoEn
        {
            get { return _modificadoEn; }
            set
            {
                if (_modificadoEn != value)
                {
                    _modificadoEn = value;
                    OnPropertyChanged("ModificadoEn");
                }
            }
        }
        private string _modificadoEn;
    
        [DataMember]
        public System.DateTime ModificadoEl
        {
            get { return _modificadoEl; }
            set
            {
                if (_modificadoEl != value)
                {
                    _modificadoEl = value;
                    OnPropertyChanged("ModificadoEl");
                }
            }
        }
        private System.DateTime _modificadoEl;

        #endregion
        #region Navigation Properties
    
        [DataMember]
        public Entidad Entidad
        {
            get { return _entidad; }
            set
            {
                if (!ReferenceEquals(_entidad, value))
                {
                    var previousValue = _entidad;
                    _entidad = value;
                    FixupEntidad(previousValue);
                    OnNavigationPropertyChanged("Entidad");
                }
            }
        }
        private Entidad _entidad;
    
        [DataMember]
        public EstadoPersona EstadoPersona
        {
            get { return _estadoPersona; }
            set
            {
                if (!ReferenceEquals(_estadoPersona, value))
                {
                    var previousValue = _estadoPersona;
                    _estadoPersona = value;
                    FixupEstadoPersona(previousValue);
                    OnNavigationPropertyChanged("EstadoPersona");
                }
            }
        }
        private EstadoPersona _estadoPersona;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            Entidad = null;
            EstadoPersona = null;
        }

        #endregion
        #region Association Fixup
    
        private void FixupEntidad(Entidad previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.Persona.Contains(this))
            {
                previousValue.Persona.Remove(this);
            }
    
            if (Entidad != null)
            {
                if (!Entidad.Persona.Contains(this))
                {
                    Entidad.Persona.Add(this);
                }
    
                IdEntidad = Entidad.IdEntidad;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Entidad")
                    && (ChangeTracker.OriginalValues["Entidad"] == Entidad))
                {
                    ChangeTracker.OriginalValues.Remove("Entidad");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Entidad", previousValue);
                }
                if (Entidad != null && !Entidad.ChangeTracker.ChangeTrackingEnabled)
                {
                    Entidad.StartTracking();
                }
            }
        }
    
        private void FixupEstadoPersona(EstadoPersona previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.Persona.Contains(this))
            {
                previousValue.Persona.Remove(this);
            }
    
            if (EstadoPersona != null)
            {
                if (!EstadoPersona.Persona.Contains(this))
                {
                    EstadoPersona.Persona.Add(this);
                }
    
                IdEstadoPersona = EstadoPersona.IdEstadoPersona;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("EstadoPersona")
                    && (ChangeTracker.OriginalValues["EstadoPersona"] == EstadoPersona))
                {
                    ChangeTracker.OriginalValues.Remove("EstadoPersona");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("EstadoPersona", previousValue);
                }
                if (EstadoPersona != null && !EstadoPersona.ChangeTracker.ChangeTrackingEnabled)
                {
                    EstadoPersona.StartTracking();
                }
            }
        }

        #endregion
    }
}
